package ee.taltech.fooddeliveryapp.database;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Interface for the WeatherData object. Provides CRUD operations for manipulating data in the database.
 */
@Repository
public interface WeatherDataRepository extends JpaRepository<WeatherData, Long> {

    /**
     * Returns the latest weather data for a given city by the city's WMO code.
     * The method is auto generated by Spring Boot because of the naming scheme.
     * @param wmoCode WMO code of the city
     * @return Latest weather data from the specfied city
     */
    WeatherData findByWmoCodeOrderByTimeStampDesc(Integer wmoCode);
}
