package ee.taltech.fooddeliveryapp.database;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Interface for the WeatherData object. Provides CRUD operations for manipulating data in the database.
 */
@Repository
public interface WeatherDataRepository extends JpaRepository<WeatherData, Long> {

    /**
     * Returns the latest weather data for a given city by the weather station's WMO code.
     * The method is auto generated by Spring Boot because of the naming scheme.
     *
     * @param wmoCode WMO code of the weather station
     * @return Latest weather data from the specfied city
     */
    WeatherData findByWmoCodeOrderByTimeStampDesc(Integer wmoCode);

    /**
     * Returns the weather data for a given city by the weather station's WMO code.
     * The weather data returned is the closest match to the target time stamp.
     * The method is auto generated by Spring Boot because of the naming scheme.
     *
     * @param wmoCode WMO code of the weather station
     * @param timeStamp Targeted time for the weather data
     * @return Closest matching weather data for the targeted time
     */
    WeatherData findFirstByWmoCodeAndTimeStampLessThanEqualOrderByTimeStampDesc(Integer wmoCode, long timeStamp);
}
